=== elucidario/elucidario.art/packages/mdorim/src/schemas/mapping/mapping.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "https://elucidario.art/mdorim/schemas/mapping/mapping.json",
    "title": "Mapping",
    "description": "Describe a interface to declare property mappings between two data models in the context of Elucid√°rio.art.",
    "type": "object",
    "version": "0.1.0",
    "properties": {
        "mapping_id": {
            "type": "integer",
            "title": "Mapping ID",
            "description": "Unique identifier of the mapping."
        },
        "name": {
            "type": "string",
            "title": "Name",
            "description": "Name of the mapping in kebab-case."
        },
        "title": {
            "type": "string",
            "title": "Title",
            "description": "Title of the mapping."
        },
        "description": {
            "type": "string",
            "title": "Description",
            "description": "Description of the mapping."
        },
        "author": {
            "type": "integer",
            "title": "Author",
            "description": "ID of the Author of the mapping."
        },
        "guid": {
            "$ref": "<local>/core.json#/definitions/guid"
        },

        "standard": {
            "type": "string",
            "title": "Standard",
            "description": "Name of the standard to be mapped."
        },

        "standard_uri": {
            "type": "string",
            "title": "Standard URI",
            "description": "URI of the standard to be mapped."
        },

        "version": {
            "description": "Version of schema file. Use semantic versioning: MAJOR.MINOR.PATCH.",
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "created": {
            "type": "string",
            "format": "date-time",
            "title": "Created",
            "description": "Date and time of creation of the mapping."
        },
        "modified": {
            "type": "string",
            "format": "date-time",
            "title": "Modified",
            "description": "Date and time of last modification of the mapping."
        },
        "mapping": {
            "type": "array",
            "items": {
                "$ref": "./prop_map.json"
            }
        }
    },
    "required": [
        "version",
        "name",
        "title",
        "author",
        "standard",
        "created",
        "modified",
        "mapping"
    ],
    "additionalProperties": false
}

=== elucidario/elucidario.art/publications/dissertacao-mestrado/content/pt-br/elucidario/cmek/mapping.json
{
    "mapping_id": 1,
    "name": "museologico-mdorim",
    "title": "BD Museológica da Casa Museu Ema Klabin para Mdorim/Linked Art",
    "description": "Descreve o mapeamento entre a BD Museológica utilizada pela Casa Museu Ema Klabin para documentar sua coleção para o modelo Mdorim utilizado pelo Elucidário.art",
    "author": 1,
    "standard": "BD Museológica Casa Museu Ema Klabin",
    "version": "1.0",
    "created": "2023-10-23",
    "modified": "2023-10-23",
    "mapping": [
        {
            "map_id": 1,
            "prop_name": "identified_by",
            "entity_type": "Object",
            "external_prop_name": "NomeTítulo",
            "external_prop_type": "string",
            "map_value": [
                {
                    "type": "Name",
                    "content": "<valor a ser preenchido pelo usuário>",
                    "classified_as": [
                        {
                            "id": "https://vocab.getty.edu/aat/300417199",
                            "label": "descriptive titles"
                        }
                    ]
                }
            ]
        },
        {
            "map_id": 34,
            "prop_name": "attributed_by",
            "entity_type": "Object",
            "external_prop_name": "LocalizaçãoOriginal",
            "external_prop_type": "string",
            "map_value": [
                {
                    "type": "AttributeAssignment",
                    "classified_as": [
                        {
                            "type": "Concept",
                            "id": "https://vocab.getty.edu/aat/300248479",
                            "_label": "location (physical position)"
                        }
                    ],
                    "identified_by": [
                        {
                            "type": "Name",
                            "content": "Localização Original",
                            "classified_as": [
                                {
                                    "type": "Concept",
                                    "id": "https://vocab.getty.edu/aat/300404669",
                                    "_label": "display information"
                                }
                            ]
                        }
                    ],
                    "assigned": "<valor a ser preenchido pelo usuário>"
                }
            ]
        }
    ]
}

=== elucidario/elucidario.art/packages/mdorim/src/mapping/mapping_test.json
{
    "name": "teste-mapeamento",
    "title": "Teste de mapeamento",
    "description": "Teste de mapeamento de propriedades de identificação de entidades.",
    "author": 1,
    "created": "2021-03-18T15:00:00",
    "modified": "2021-03-18T15:00:00",
    "version": "0.1.0",
    "standard": "Spectrum",
    "mapping": [
        {
            "map_id": 1,
            "entity_type": "Concept",
            "prop_name": "identified_by",
            "external_prop_name": "Object entry",
            "external_prop_type": "string",
            "map_value": {
                "type": "Identifier",
                "classified_as": [
                    {
                        "id": "http://vocab.getty.edu/aat/300312355",
                        "type": "Type",
                        "_label": "aat:accession numbers"
                    }
                ]
            },
            "status": "active"
        }
    ]
}
