=== elucidario/elucidario.art/packages/pub-gen/lib/presets/abnt/schemas/referencias/livro.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Schema para referência bibliográfica de um livro",
    "description": "Schema para que descreve uma referência bibliográfica de um livro.",
    "type": "object",
    "properties": {
        "titulo": {
            "description": "Título do livro",
            "type": "string"
        },
        "autores": {
            "$ref": "./referencias/autor.json/#definitions/autores"
        },
        "ano": {
            "description": "Ano de publicação do livro",
            "type": "integer"
        },
        "capitulo": {
            "description": "Capítulo do livro",
            "type": "object",
            "properties": {
                "titulo": {
                    "description": "Título do capítulo",
                    "type": "string"
                },
                "autores": {
                    "$ref": "./referencias/autor.json/#definitions/autores"
                },
                "paginas": {
                    "description": "Páginas do capítulo",
                    "type": "object",
                    "properties": {
                        "inicio": {
                            "description": "Página inicial do capítulo",
                            "type": "integer"
                        },
                        "fim": {
                            "description": "Página final do capítulo",
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "editora": {
            "description": "Editora do livro",
            "type": "string"
        },
        "cidade": {
            "description": "Cidade de publicação do livro",
            "type": "string"
        },
        "edicao": {
            "description": "Edição do livro",
            "type": "integer"
        },
        "volume": {
            "description": "Volume do livro",
            "type": "integer"
        },
        "paginas": {
            "description": "Número de páginas do livro",
            "type": "integer"
        },
        "isbn": {
            "description": "ISBN do livro",
            "type": "string"
        },
        "url": {
            "description": "URL do livro",
            "type": "string"
        },
        "doi": {
            "description": "DOI do livro",
            "type": "string"
        },
        "tipo": {
            "description": "Tipo de referência bibliográfica",
            "type": "string",
            "const": "livro"
        }
    }
}

=== elucidario/elucidario.art/publications/dissertacao-mestrado/references/abnt/livro.json
{
    "titulo": "Aprendendo a programar em C",
    "autores": [
        {
            "nome": "Paulo",
            "sobrenome": "Silva"
        },
        {
            "nome": "João",
            "sobrenome": "Santos"
        }
    ],
    "ano": 2015,
    "editora": "Editora do Brasil",
    "edicao": 1,
    "isbn": "978-85-12345-67-8",
    "paginas": 300,
    "cidade": "São Paulo",
    "tipo": "livro"
}
